/**
 * Full list at https://discord.com/developers/docs/topics/gateway#list-of-intents.
 */
enum Event {
  READY = 'READY',
  GUILD_CREATE = 'GUILD_CREATE',
  GUILD_UPDATE = 'GUILD_UPDATE',
  GUILD_DELETE = 'GUILD_DELETE',
  GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE',
  GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE',
  GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE',
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_UPDATE = 'CHANNEL_UPDATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  INTERACTION_CREATE = 'INTERACTION_CREATE',
  MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
  MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
  MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL',
  MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI',
}

export default Event;
